from pyspark import pipelines as dp
from pyspark.sql import functions as F


# Create a gold-layer table showing the highest-revenue zones for today.
@dp.table(comment="Top 10 zones by revenue for completed rides today.")
def gold_top_zones():
    # Read silver-layer ride events and keep only records from the current date.
    today = (
        spark.read.table("silver_ride_events")
        .filter(F.col("event_date") == F.current_date())
    )

    return (
        # Keep only rides that were successfully completed.
        today.filter(F.col("status") == "completed")

        # Group completed rides by zone and city.
        .groupBy("zone_id", "city")

        # Calculate revenue, ride volume, fare, and distance metrics per zone.
        .agg(
            # Total revenue generated by completed rides in the zone.
            F.round(F.sum("final_fare"), 2).alias("total_revenue_inr"),

            # Number of completed rides in the zone.
            F.count("ride_id").alias("completed_rides"),

            # Average fare for completed rides in the zone.
            F.round(F.avg("final_fare"), 2).alias("avg_fare_inr"),

            # Average trip distance for completed rides in the zone.
            F.round(F.avg("distance_km"), 1).alias("avg_distance_km"),
        )

        # Rank zones by revenue from highest to lowest.
        .orderBy(F.col("total_revenue_inr").desc())

        # Return only the top 10 revenue-generating zones.
        .limit(10)
    )